/**
 * Emoji shortcode to Unicode mapping
 * Supports common emoji shortcodes used in chat applications
 */

export const EMOJI_MAP = {
	// Smileys & Emotion
	smile: "😄",
	grin: "😁",
	joy: "😂",
	rofl: "🤣",
	relaxed: "☺️",
	blush: "😊",
	innocent: "😇",
	wink: "😉",
	relieved: "😌",
	heart_eyes: "😍",
	kissing_heart: "😘",
	yum: "😋",
	stuck_out_tongue: "😛",
	stuck_out_tongue_winking_eye: "😜",
	zany_face: "🤪",
	thinking: "🤔",
	neutral_face: "😐",
	expressionless: "😑",
	no_mouth: "😶",
	smirk: "😏",
	unamused: "😒",
	roll_eyes: "🙄",
	grimacing: "😬",
	lying_face: "🤥",
	pensive: "😔",
	sleepy: "😪",
	drooling_face: "🤤",
	sleeping: "😴",
	mask: "😷",
	face_with_thermometer: "🤒",
	face_with_head_bandage: "🤕",
	nauseated_face: "🤢",
	sneezing_face: "🤧",
	dizzy_face: "😵",
	exploding_head: "🤯",
	sunglasses: "😎",
	nerd_face: "🤓",
	confused: "😕",
	slightly_frowning_face: "🙁",
	frowning_face: "☹️",
	persevere: "😣",
	confounded: "😖",
	tired_face: "😫",
	weary: "😩",
	cry: "😢",
	sob: "😭",
	triumph: "😤",
	angry: "😠",
	rage: "😡",
	face_with_symbols_on_mouth: "🤬",
	scream: "😱",
	fearful: "😨",
	cold_sweat: "😰",
	disappointed_relieved: "😥",
	sweat: "😓",
	hugs: "🤗",
	saluting_face: "🫡",
	shushing_face: "🤫",
	thinking_face: "🤔",
	zipper_mouth_face: "🤐",
	raised_eyebrow: "🤨",
	neutral_face_2: "😐",
	smiling_face_with_tear: "🥲",

	// Gestures & Body Parts
	"+1": "👍",
	thumbsup: "👍",
	"-1": "👎",
	thumbsdown: "👎",
	ok_hand: "👌",
	punch: "👊",
	fist: "✊",
	wave: "👋",
	clap: "👏",
	pray: "🙏",
	handshake: "🤝",
	muscle: "💪",
	point_up: "☝️",
	point_down: "👇",
	point_left: "👈",
	point_right: "👉",
	raised_hand: "✋",
	hand: "✋",
	vulcan_salute: "🖖",
	ok: "👌",
	crossed_fingers: "🤞",
	love_you_gesture: "🤟",
	metal: "🤘",
	call_me_hand: "🤙",
	raising_hand: "🙋",

	// Hearts & Symbols
	heart: "❤️",
	orange_heart: "🧡",
	yellow_heart: "💛",
	green_heart: "💚",
	blue_heart: "💙",
	purple_heart: "💜",
	black_heart: "🖤",
	white_heart: "🤍",
	brown_heart: "🤎",
	broken_heart: "💔",
	heart_on_fire: "❤️‍🔥",
	mending_heart: "❤️‍🩹",
	sparkling_heart: "💖",
	heartpulse: "💗",
	heartbeat: "💓",
	revolving_hearts: "💞",
	two_hearts: "💕",
	cupid: "💘",
	gift_heart: "💝",
	star: "⭐",
	sparkles: "✨",
	boom: "💥",
	fire: "🔥",
	zap: "⚡",
	rocket: "🚀",
	tada: "🎉",
	confetti_ball: "🎊",
	balloon: "🎈",

	// Nature & Animals
	dog: "🐶",
	cat: "🐱",
	mouse: "🐭",
	hamster: "🐹",
	rabbit: "🐰",
	fox: "🦊",
	bear: "🐻",
	panda: "🐼",
	koala: "🐨",
	tiger: "🐯",
	lion: "🦁",
	cow: "🐮",
	pig: "🐷",
	frog: "🐸",
	monkey: "🐵",
	see_no_evil: "🙈",
	hear_no_evil: "🙉",
	speak_no_evil: "🙊",
	unicorn: "🦄",
	bee: "🐝",
	bug: "🐛",
	butterfly: "🦋",
	snail: "🐌",
	turtle: "🐢",
	snake: "🐍",
	lizard: "🦎",
	t_rex: "🦖",
	penguin: "🐧",
	bird: "🐦",
	dove: "🕊️",
	eagle: "🦅",
	duck: "🦆",
	owl: "🦉",
	fish: "🐟",
	dolphin: "🐬",
	whale: "🐳",
	octopus: "🐙",
	crab: "🦀",
	shrimp: "🦐",
	squid: "🦑",

	// Food & Drink
	apple: "🍎",
	banana: "🍌",
	orange: "🍊",
	lemon: "🍋",
	watermelon: "🍉",
	grapes: "🍇",
	strawberry: "🍓",
	cherries: "🍒",
	peach: "🍑",
	pineapple: "🍍",
	avocado: "🥑",
	broccoli: "🥦",
	carrot: "🥕",
	corn: "🌽",
	hot_pepper: "🌶️",
	bread: "🍞",
	croissant: "🥐",
	baguette: "🥖",
	cheese: "🧀",
	egg: "🥚",
	bacon: "🥓",
	pancakes: "🥞",
	pizza: "🍕",
	hamburger: "🍔",
	fries: "🍟",
	hotdog: "🌭",
	taco: "🌮",
	burrito: "🌯",
	sushi: "🍣",
	ramen: "🍜",
	spaghetti: "🍝",
	curry: "🍛",
	rice: "🍚",
	bento: "🍱",
	icecream: "🍦",
	cake: "🍰",
	birthday: "🎂",
	cookie: "🍪",
	chocolate_bar: "🍫",
	candy: "🍬",
	doughnut: "🍩",
	coffee: "☕",
	tea: "🍵",
	beer: "🍺",
	wine_glass: "🍷",
	cocktail: "🍹",
	tropical_drink: "🍹",
	champagne: "🍾",
	milk_glass: "🥛",

	// Activities & Sports
	soccer: "⚽",
	basketball: "🏀",
	football: "🏈",
	baseball: "⚾",
	tennis: "🎾",
	volleyball: "🏐",
	trophy: "🏆",
	medal_sports: "🏅",
	first_place_medal: "🥇",
	second_place_medal: "🥈",
	third_place_medal: "🥉",
	dart: "🎯",
	video_game: "🎮",
	joystick: "🕹️",
	game_die: "🎲",
	guitar: "🎸",
	musical_note: "🎵",
	headphones: "🎧",
	microphone: "🎤",
	movie_camera: "🎥",
	art: "🎨",
	paintbrush: "🖌️",

	// Travel & Places
	car: "🚗",
	taxi: "🚕",
	bus: "🚌",
	train: "🚆",
	airplane: "✈️",
	bike: "🚲",
	scooter: "🛴",
	ship: "🚢",
	speedboat: "🚤",
	helicopter: "🚁",
	flying_saucer: "🛸",
	house: "🏠",
	building: "🏢",
	hotel: "🏨",
	hospital: "🏥",
	school: "🏫",
	tent: "⛺",
	mountain: "⛰️",
	beach: "🏖️",
	desert: "🏜️",
	island: "🏝️",
	cityscape: "🏙️",
	sunrise: "🌅",
	sunset: "🌇",
	night_with_stars: "🌃",
	rainbow: "🌈",
	umbrella: "☂️",
	snowflake: "❄️",
	sun: "☀️",
	cloud: "☁️",
	lightning: "⚡",
	tornado: "🌪️",
	fog: "🌫️",

	// Objects
	watch: "⌚",
	phone: "📱",
	computer: "💻",
	keyboard: "⌨️",
	printer: "🖨️",
	camera: "📷",
	bulb: "💡",
	book: "📖",
	books: "📚",
	pencil: "✏️",
	pen: "🖊️",
	memo: "📝",
	briefcase: "💼",
	calendar: "📅",
	pushpin: "📌",
	paperclip: "📎",
	scissors: "✂️",
	lock: "🔒",
	unlock: "🔓",
	key: "🔑",
	hammer: "🔨",
	wrench: "🔧",
	gear: "⚙️",
	link: "🔗",
	magnet: "🧲",
	bomb: "💣",
	pill: "💊",
	syringe: "💉",
	thermometer: "🌡️",
	door: "🚪",
	bed: "🛏️",
	couch: "🛋️",
	toilet: "🚽",
	shower: "🚿",
	bathtub: "🛁",

	// Symbols
	red_circle: "🔴",
	blue_circle: "🔵",
	white_circle: "⚪",
	black_circle: "⚫",
	red_square: "🟥",
	blue_square: "🟦",
	orange_square: "🟧",
	yellow_square: "🟨",
	green_square: "🟩",
	purple_square: "🟪",
	brown_square: "🟫",
	check: "✅",
	x: "❌",
	question: "❓",
	exclamation: "❗",
	warning: "⚠️",
	no_entry: "⛔",
	radioactive: "☢️",
	biohazard: "☣️",
	arrow_up: "⬆️",
	arrow_down: "⬇️",
	arrow_left: "⬅️",
	arrow_right: "➡️",
	arrow_up_down: "↕️",
	left_right_arrow: "↔️",
	arrows_clockwise: "🔃",
	arrows_counterclockwise: "🔄",
	rewind: "⏪",
	fast_forward: "⏩",
	arrow_forward: "▶️",
	arrow_backward: "◀️",
	arrow_up_small: "🔼",
	arrow_down_small: "🔽",
	play_pause: "⏯️",
	stop_button: "⏹️",
	record_button: "⏺️",

	// Flags (popular ones)
	flag_us: "🇺🇸",
	flag_gb: "🇬🇧",
	flag_es: "🇪🇸",
	flag_fr: "🇫🇷",
	flag_de: "🇩🇪",
	flag_it: "🇮🇹",
	flag_jp: "🇯🇵",
	flag_kr: "🇰🇷",
	flag_cn: "🇨🇳",
	flag_mx: "🇲🇽",
	flag_br: "🇧🇷",
	flag_ca: "🇨🇦",
	flag_au: "🇦🇺",
	flag_in: "🇮🇳",
	flag_ru: "🇷🇺",
	checkered_flag: "🏁",
	triangular_flag: "🚩",
	rainbow_flag: "🏳️‍🌈",
	pirate_flag: "🏴‍☠️",
} as const satisfies Record<string, string>;

/**
 * Type representing all valid emoji shortcodes
 */
export type EmojiShortcode = keyof typeof EMOJI_MAP;

/**
 * Type representing all emoji Unicode characters
 */
export type EmojiUnicode = (typeof EMOJI_MAP)[EmojiShortcode];

/**
 * Get emoji Unicode from shortcode with type-safe overload for known shortcodes
 * @param shortcode - Emoji shortcode (e.g., "smile")
 * @returns Emoji Unicode character or undefined if not found
 */
export function getEmoji<T extends EmojiShortcode>(
	shortcode: T,
): (typeof EMOJI_MAP)[T];
export function getEmoji(shortcode: string): string | undefined;
export function getEmoji(shortcode: string): string | undefined {
	return EMOJI_MAP[shortcode as EmojiShortcode];
}

/**
 * Get all available emoji shortcodes
 */
export function getAllShortcodes() {
	return Object.keys(EMOJI_MAP) as EmojiShortcode[];
}

/**
 * Check if a shortcode exists in the emoji map (type guard)
 * @param shortcode - String to check
 * @returns True if shortcode is valid, with type narrowing
 */
export function hasEmoji(shortcode: string): shortcode is EmojiShortcode {
	return shortcode in EMOJI_MAP;
}

/**
 * Emoji categories for picker UI
 * NOTE: A subset of this data is duplicated in client-side JavaScript (src/server/index.ts)
 * for the inline HTML bundle. The client uses a smaller emoji set (~75 emojis) for the picker UI,
 * while the server supports the full set (376+ emojis) for shortcode conversion.
 * Strategy: Client inserts Unicode directly from picker, server converts typed shortcodes.
 * Keep categories in sync if adding new UI categories.
 */
export const EMOJI_CATEGORIES = {
	"Smileys & People": [
		"smile",
		"grin",
		"joy",
		"heart_eyes",
		"wink",
		"blush",
		"thinking",
		"neutral_face",
		"expressionless",
		"unamused",
		"roll_eyes",
		"cry",
		"sob",
		"angry",
		"scream",
		"sunglasses",
		"nerd_face",
	],
	Gestures: [
		"thumbsup",
		"thumbsdown",
		"ok_hand",
		"wave",
		"clap",
		"pray",
		"muscle",
		"point_up",
		"point_right",
		"raised_hand",
	],
	Hearts: [
		"heart",
		"orange_heart",
		"yellow_heart",
		"green_heart",
		"blue_heart",
		"purple_heart",
		"broken_heart",
		"sparkling_heart",
		"two_hearts",
	],
	Symbols: [
		"fire",
		"star",
		"sparkles",
		"zap",
		"boom",
		"rocket",
		"tada",
		"balloon",
		"trophy",
		"check",
		"x",
		"warning",
	],
	"Nature & Animals": [
		"dog",
		"cat",
		"rabbit",
		"fox",
		"bear",
		"panda",
		"tiger",
		"lion",
		"monkey",
		"unicorn",
		"bird",
		"penguin",
		"fish",
	],
	"Food & Drink": [
		"apple",
		"banana",
		"pizza",
		"hamburger",
		"cake",
		"icecream",
		"coffee",
		"beer",
		"wine_glass",
		"taco",
		"sushi",
		"ramen",
	],
	Activities: [
		"soccer",
		"basketball",
		"trophy",
		"first_place_medal",
		"video_game",
		"guitar",
		"microphone",
		"art",
		"camera",
	],
	"Travel & Places": [
		"car",
		"airplane",
		"rocket",
		"house",
		"beach",
		"mountain",
		"rainbow",
		"sun",
		"cloud",
		"snowflake",
	],
} as const;

/**
 * Type representing all emoji category names
 */
export type EmojiCategoryName = keyof typeof EMOJI_CATEGORIES;

/**
 * Type representing emojis within a specific category
 */
export type EmojiInCategory<T extends EmojiCategoryName> =
	(typeof EMOJI_CATEGORIES)[T][number];
